/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedChatsIdRouteImport } from './routes/_authenticated/chats.$id'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as AuthenticatedStudioAvatarRouteImport } from './routes/_authenticated/studio.avatar'
import { Route as AuthenticatedStudioCallsRouteImport } from './routes/_authenticated/studio.calls'
import { Route as AuthenticatedStudioInstructionsRouteImport } from './routes/_authenticated/studio.instructions'
import { Route as AuthenticatedStudioKnowledgeRouteImport } from './routes/_authenticated/studio.knowledge'
import { Route as AuthenticatedStudioPersonalityRouteImport } from './routes/_authenticated/studio.personality'
import { Route as AuthenticatedStudioTestRouteImport } from './routes/_authenticated/studio.test'
import { Route as AuthenticatedStudioVoiceRouteImport } from './routes/_authenticated/studio.voice'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatsRoute,
} as any)
const AuthenticatedChatsIdRoute = AuthenticatedChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatsRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioAvatarRoute =
  AuthenticatedStudioAvatarRouteImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioCallsRoute =
  AuthenticatedStudioCallsRouteImport.update({
    id: '/calls',
    path: '/calls',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioInstructionsRoute =
  AuthenticatedStudioInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioKnowledgeRoute =
  AuthenticatedStudioKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioPersonalityRoute =
  AuthenticatedStudioPersonalityRouteImport.update({
    id: '/personality',
    path: '/personality',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioTestRoute = AuthenticatedStudioTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedStudioRoute,
} as any)
const AuthenticatedStudioVoiceRoute =
  AuthenticatedStudioVoiceRouteImport.update({
    id: '/voice',
    path: '/voice',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRouteWithChildren
  '/contacts': typeof AuthenticatedContactsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/studio/avatar': typeof AuthenticatedStudioAvatarRoute
  '/studio/calls': typeof AuthenticatedStudioCallsRoute
  '/studio/instructions': typeof AuthenticatedStudioInstructionsRoute
  '/studio/knowledge': typeof AuthenticatedStudioKnowledgeRoute
  '/studio/personality': typeof AuthenticatedStudioPersonalityRoute
  '/studio/test': typeof AuthenticatedStudioTestRoute
  '/studio/voice': typeof AuthenticatedStudioVoiceRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/studio/avatar': typeof AuthenticatedStudioAvatarRoute
  '/studio/calls': typeof AuthenticatedStudioCallsRoute
  '/studio/instructions': typeof AuthenticatedStudioInstructionsRoute
  '/studio/knowledge': typeof AuthenticatedStudioKnowledgeRoute
  '/studio/personality': typeof AuthenticatedStudioPersonalityRoute
  '/studio/test': typeof AuthenticatedStudioTestRoute
  '/studio/voice': typeof AuthenticatedStudioVoiceRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRouteWithChildren
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRouteWithChildren
  '/_authenticated/chats/$id': typeof AuthenticatedChatsIdRoute
  '/_authenticated/studio/avatar': typeof AuthenticatedStudioAvatarRoute
  '/_authenticated/studio/calls': typeof AuthenticatedStudioCallsRoute
  '/_authenticated/studio/instructions': typeof AuthenticatedStudioInstructionsRoute
  '/_authenticated/studio/knowledge': typeof AuthenticatedStudioKnowledgeRoute
  '/_authenticated/studio/personality': typeof AuthenticatedStudioPersonalityRoute
  '/_authenticated/studio/test': typeof AuthenticatedStudioTestRoute
  '/_authenticated/studio/voice': typeof AuthenticatedStudioVoiceRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/calls'
    | '/chats'
    | '/contacts'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/studio'
    | '/chats/$id'
    | '/studio/avatar'
    | '/studio/calls'
    | '/studio/instructions'
    | '/studio/knowledge'
    | '/studio/personality'
    | '/studio/test'
    | '/studio/voice'
    | '/u/$username'
    | '/chats/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/calls'
    | '/contacts'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/chats/$id'
    | '/studio/avatar'
    | '/studio/calls'
    | '/studio/instructions'
    | '/studio/knowledge'
    | '/studio/personality'
    | '/studio/test'
    | '/studio/voice'
    | '/u/$username'
    | '/chats'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/calls'
    | '/_authenticated/chats'
    | '/_authenticated/contacts'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/chats/$id'
    | '/_authenticated/studio/avatar'
    | '/_authenticated/studio/calls'
    | '/_authenticated/studio/instructions'
    | '/_authenticated/studio/knowledge'
    | '/_authenticated/studio/personality'
    | '/_authenticated/studio/test'
    | '/_authenticated/studio/voice'
    | '/_authenticated/u/$username'
    | '/_authenticated/chats/'
    | '/_authenticated/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
    '/_authenticated/chats/$id': {
      id: '/_authenticated/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsIdRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/avatar': {
      id: '/_authenticated/studio/avatar'
      path: '/avatar'
      fullPath: '/studio/avatar'
      preLoaderRoute: typeof AuthenticatedStudioAvatarRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/calls': {
      id: '/_authenticated/studio/calls'
      path: '/calls'
      fullPath: '/studio/calls'
      preLoaderRoute: typeof AuthenticatedStudioCallsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/instructions': {
      id: '/_authenticated/studio/instructions'
      path: '/instructions'
      fullPath: '/studio/instructions'
      preLoaderRoute: typeof AuthenticatedStudioInstructionsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/knowledge': {
      id: '/_authenticated/studio/knowledge'
      path: '/knowledge'
      fullPath: '/studio/knowledge'
      preLoaderRoute: typeof AuthenticatedStudioKnowledgeRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/personality': {
      id: '/_authenticated/studio/personality'
      path: '/personality'
      fullPath: '/studio/personality'
      preLoaderRoute: typeof AuthenticatedStudioPersonalityRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/test': {
      id: '/_authenticated/studio/test'
      path: '/test'
      fullPath: '/studio/test'
      preLoaderRoute: typeof AuthenticatedStudioTestRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/voice': {
      id: '/_authenticated/studio/voice'
      path: '/voice'
      fullPath: '/studio/voice'
      preLoaderRoute: typeof AuthenticatedStudioVoiceRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedChatsRouteChildren {
  AuthenticatedChatsIdRoute: typeof AuthenticatedChatsIdRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedChatsRouteChildren: AuthenticatedChatsRouteChildren = {
  AuthenticatedChatsIdRoute: AuthenticatedChatsIdRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedChatsRouteWithChildren =
  AuthenticatedChatsRoute._addFileChildren(AuthenticatedChatsRouteChildren)

interface AuthenticatedStudioRouteChildren {
  AuthenticatedStudioAvatarRoute: typeof AuthenticatedStudioAvatarRoute
  AuthenticatedStudioCallsRoute: typeof AuthenticatedStudioCallsRoute
  AuthenticatedStudioInstructionsRoute: typeof AuthenticatedStudioInstructionsRoute
  AuthenticatedStudioKnowledgeRoute: typeof AuthenticatedStudioKnowledgeRoute
  AuthenticatedStudioPersonalityRoute: typeof AuthenticatedStudioPersonalityRoute
  AuthenticatedStudioTestRoute: typeof AuthenticatedStudioTestRoute
  AuthenticatedStudioVoiceRoute: typeof AuthenticatedStudioVoiceRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedStudioRouteChildren: AuthenticatedStudioRouteChildren = {
  AuthenticatedStudioAvatarRoute: AuthenticatedStudioAvatarRoute,
  AuthenticatedStudioCallsRoute: AuthenticatedStudioCallsRoute,
  AuthenticatedStudioInstructionsRoute: AuthenticatedStudioInstructionsRoute,
  AuthenticatedStudioKnowledgeRoute: AuthenticatedStudioKnowledgeRoute,
  AuthenticatedStudioPersonalityRoute: AuthenticatedStudioPersonalityRoute,
  AuthenticatedStudioTestRoute: AuthenticatedStudioTestRoute,
  AuthenticatedStudioVoiceRoute: AuthenticatedStudioVoiceRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedStudioRouteWithChildren =
  AuthenticatedStudioRoute._addFileChildren(AuthenticatedStudioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRouteWithChildren
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRouteWithChildren
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRouteWithChildren,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRouteWithChildren,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
